# conda env create -f environment.yaml  
# conda activate keal

name: keal

channels:
  - conda-forge

dependencies:
  - python=3.12.0
  - pip
  - numpy=1.26.2
  - matplotlib=3.8.2
  - pandas=2.1.4
  - requests=2.31.0
  - pip:
  # For regular pip packages
    - yfinance==0.2.37
    - scipy==1.13.0